### ISSUE TITLE
Page 1 is not scraped in this case

### ISSUE THREAD

**Issue by anjannair** [sahilgupta/sbi_forex_rates#1]
Only page 2 of the PDF is scraped. Scraping of page 1 can also be done and stored inside `csv_files` under separate folders for page 1 and page 2.

The header for page 1 begins at index 2 something like this

```python
header_row = lines[2]
```

And the for loop can run from index 3

```python
for line in lines[3:]:
```

**Rest of the code remains the same for page 1**

**Comment by sahilgupta** [comment]
Page 1 was intentionally ignored because the reference rates are only on Page 2. SBI calls this out at the top of the Page 2.
Why do you think Page 1 data is useful?

**Comment by anjannair** [comment]
@sahilgupta I feel both pages are equally important. The first one's header mentions it is for transactions below 10 lacs.

**Comment by sahilgupta** [comment]
The goal of this project is to track forex rates relevant for Income Tax purposes, which are quoted on the 2nd page. 

Reference rates to be used for converting capital gains/foreign income are _independent_ of the size of the transaction. 
Even a 100 USD transaction must use the reference rates as a 10000 USD transaction.

Rates on the 1st page are thus not relevant.

**Comment by sahilgupta** [comment]
The goal of this project is to track forex rates relevant for Income Tax purposes, which are quoted on the 2nd page. 

Reference rates to be used for converting capital gains/foreign income are _independent_ of the size of the transaction. 
Even a 100 USD transaction must use the reference rates as a 10000 USD transaction.

Rates on the 1st page are thus not relevant.
