### ISSUE TITLE
Pulling Data Directly into Excel for a particular Date

### ISSUE THREAD

**Issue by nipunmehar** [sahilgupta/sbi_forex_rates#3]
Great work Sahil and Shivam!
This information has been really helpful.
Can data be directly imported into an Excel sheet for a specific date? Doing so would enhance data accessibility.

**Comment by sahilgupta** [comment]
I am not sure, I follow, @nipunmehar. Can you please elaborate what you are trying to achieve?

Any of the CSV files can be imported into Excel where you can filter or do a VLOOKUP for specific dates.

**Comment by nipunmehar** [comment]
I have a excel sheet where I am tracking all my US holdings. What I am currently doing is searching here for exchange rates for individual dates for each of my holdings and then manually filing them in my excel sheet. I wondered if it was possible to directly populate data per date in my excel sheet from this repository.

**Comment by sahilgupta** [comment]
Got it.

You can have all the data in one Excel sheet /tab and cross-reference it from the holdings data using =VLOOKUP function, having date as the lookup key.

No need to manually fill.

**Comment by nipunmehar** [comment]
Thanks Sahil!
